package config

import (
	"bytes"
	"compress/gzip"
	"io"
)

// Function generated by github.com/jteeuwen/go-bindata
// This returns the binary form of a libspotify API key.
// This can't be included in the source code so you need your own.
// Get yours here: https://developer.spotify.com/technologies/libspotify/keys/
func Spotify_key() []byte {
	gz, err := gzip.NewReader(bytes.NewBuffer([]byte{
		0x1f,
	}))

	if err != nil {
		panic("Decompression failed: " + err.Error())
	}

	var b bytes.Buffer
	io.Copy(&b, gz)
	gz.Close()

	return b.Bytes()
}
